// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: console/v1/console.proto

package consolev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ConsoleService_Login_FullMethodName      = "/coremesh.console.v1.ConsoleService/Login"
	ConsoleService_Logout_FullMethodName     = "/coremesh.console.v1.ConsoleService/Logout"
	ConsoleService_Execute_FullMethodName    = "/coremesh.console.v1.ConsoleService/Execute"
	ConsoleService_SampleFile_FullMethodName = "/coremesh.console.v1.ConsoleService/SampleFile"
	ConsoleService_Read_FullMethodName       = "/coremesh.console.v1.ConsoleService/Read"
)

// ConsoleServiceClient is the client API for ConsoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsoleServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// Execute ruft target_object.target_action eines Moduls auf. Enthält die
	// Antwort zip_content und ist target_directory gesetzt, entpackt das
	// Console-Plugin das ZIP dort (Berechtigung Console.ExtractZip).
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// SampleFile erzeugt aus dem Metamodell (Catalog) eine Beispieldatei.
	SampleFile(ctx context.Context, in *SampleFileRequest, opts ...grpc.CallOption) (*SampleFileResponse, error)
	// Read ruft target_object.target_action als Datenstrom auf (sdk.Reader,
	// z. B. JournalEntryItem.list): erst columns, dann rows-Blöcke, zum Schluss
	// end. Rechte wie bei Execute; target_directory wird nicht ausgewertet.
	Read(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (ConsoleService_ReadClient, error)
}

type consoleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsoleServiceClient(cc grpc.ClientConnInterface) ConsoleServiceClient {
	return &consoleServiceClient{cc}
}

func (c *consoleServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, ConsoleService_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, ConsoleService_Logout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, ConsoleService_Execute_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) SampleFile(ctx context.Context, in *SampleFileRequest, opts ...grpc.CallOption) (*SampleFileResponse, error) {
	out := new(SampleFileResponse)
	err := c.cc.Invoke(ctx, ConsoleService_SampleFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) Read(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (ConsoleService_ReadClient, error) {
	stream, err := c.cc.NewStream(ctx, &ConsoleService_ServiceDesc.Streams[0], ConsoleService_Read_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &consoleServiceReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConsoleService_ReadClient interface {
	Recv() (*ReadChunk, error)
	grpc.ClientStream
}

type consoleServiceReadClient struct {
	grpc.ClientStream
}

func (x *consoleServiceReadClient) Recv() (*ReadChunk, error) {
	m := new(ReadChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConsoleServiceServer is the server API for ConsoleService service.
// All implementations must embed UnimplementedConsoleServiceServer
// for forward compatibility
type ConsoleServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// Execute ruft target_object.target_action eines Moduls auf. Enthält die
	// Antwort zip_content und ist target_directory gesetzt, entpackt das
	// Console-Plugin das ZIP dort (Berechtigung Console.ExtractZip).
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// SampleFile erzeugt aus dem Metamodell (Catalog) eine Beispieldatei.
	SampleFile(context.Context, *SampleFileRequest) (*SampleFileResponse, error)
	// Read ruft target_object.target_action als Datenstrom auf (sdk.Reader,
	// z. B. JournalEntryItem.list): erst columns, dann rows-Blöcke, zum Schluss
	// end. Rechte wie bei Execute; target_directory wird nicht ausgewertet.
	Read(*ExecuteRequest, ConsoleService_ReadServer) error
	mustEmbedUnimplementedConsoleServiceServer()
}

// UnimplementedConsoleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConsoleServiceServer struct {
}

func (UnimplementedConsoleServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedConsoleServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedConsoleServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedConsoleServiceServer) SampleFile(context.Context, *SampleFileRequest) (*SampleFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SampleFile not implemented")
}
func (UnimplementedConsoleServiceServer) Read(*ExecuteRequest, ConsoleService_ReadServer) error {
	return status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedConsoleServiceServer) mustEmbedUnimplementedConsoleServiceServer() {}

// UnsafeConsoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsoleServiceServer will
// result in compilation errors.
type UnsafeConsoleServiceServer interface {
	mustEmbedUnimplementedConsoleServiceServer()
}

func RegisterConsoleServiceServer(s grpc.ServiceRegistrar, srv ConsoleServiceServer) {
	s.RegisterService(&ConsoleService_ServiceDesc, srv)
}

func _ConsoleService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_SampleFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).SampleFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_SampleFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).SampleFile(ctx, req.(*SampleFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConsoleServiceServer).Read(m, &consoleServiceReadServer{stream})
}

type ConsoleService_ReadServer interface {
	Send(*ReadChunk) error
	grpc.ServerStream
}

type consoleServiceReadServer struct {
	grpc.ServerStream
}

func (x *consoleServiceReadServer) Send(m *ReadChunk) error {
	return x.ServerStream.SendMsg(m)
}

// ConsoleService_ServiceDesc is the grpc.ServiceDesc for ConsoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coremesh.console.v1.ConsoleService",
	HandlerType: (*ConsoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _ConsoleService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _ConsoleService_Logout_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _ConsoleService_Execute_Handler,
		},
		{
			MethodName: "SampleFile",
			Handler:    _ConsoleService_SampleFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Read",
			Handler:       _ConsoleService_Read_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "console/v1/console.proto",
}
