// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: plugin/v1/host.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HostService_Dispatch_FullMethodName   = "/coremesh.plugin.v1.HostService/Dispatch"
	HostService_Log_FullMethodName        = "/coremesh.plugin.v1.HostService/Log"
	HostService_Query_FullMethodName      = "/coremesh.plugin.v1.HostService/Query"
	HostService_Exec_FullMethodName       = "/coremesh.plugin.v1.HostService/Exec"
	HostService_BeginTx_FullMethodName    = "/coremesh.plugin.v1.HostService/BeginTx"
	HostService_CommitTx_FullMethodName   = "/coremesh.plugin.v1.HostService/CommitTx"
	HostService_RollbackTx_FullMethodName = "/coremesh.plugin.v1.HostService/RollbackTx"
)

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostServiceClient interface {
	// Dispatch übergibt eine (object, action)-Anfrage an den Dispatcher des
	// Hosts, der sie an das zuständige Plugin weiterleitet – nach derselben
	// Match-Logik wie bei Anfragen von außen (siehe PluginService). Das
	// aufrufende Plugin kennt das Ziel-Plugin nicht.
	//
	// Der Host übernimmt request_id, tenant_id und user_id des auslösenden
	// Handle-Aufrufs, sodass Mandant und Berechtigungen über die ganze
	// Aufrufkette erhalten bleiben. Deadlines und Abbruch propagieren über gRPC.
	// Zyklen (A -> B -> A ...) begrenzt der Host über eine maximale
	// Verschachtelungstiefe pro request_id und antwortet dann mit
	// FailedPrecondition. Kein Treffer: Unimplemented.
	Dispatch(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error)
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	// Query führt ein SELECT aus und liefert die Zeilen zurück.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Exec führt INSERT/UPDATE/DELETE aus.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	// Transaktionen
	//
	// Eine Transaktion gilt für genau eine Datenbank und ist an die request_id
	// der Aufrufkette gebunden. Query/Exec laufen in ihr, wenn
	// Context.tx_ids[database] gesetzt ist – auch in Plugins, die über Dispatch
	// aufgerufen wurden. Mehrere Datenbanken werden nicht atomar verbunden.
	//
	// Commit darf nur der Eröffner (gleiche request_id, gleiches Plugin).
	// Rollback darf jeder Teilnehmer auslösen; danach ist die Transaktion
	// abgebrochen und jeder weitere Zugriff bzw. Commit liefert Aborted.
	//
	// Der Host rollt automatisch zurück, wenn die äußerste Anfrage endet, die
	// maximale Laufzeit überschritten ist oder der Plugin-Prozess abstürzt.
	// Die Zahl offener Transaktionen pro Plugin ist begrenzt
	// (ResourceExhausted).
	BeginTx(ctx context.Context, in *BeginTxRequest, opts ...grpc.CallOption) (*BeginTxResponse, error)
	CommitTx(ctx context.Context, in *CommitTxRequest, opts ...grpc.CallOption) (*CommitTxResponse, error)
	RollbackTx(ctx context.Context, in *RollbackTxRequest, opts ...grpc.CallOption) (*RollbackTxResponse, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) Dispatch(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error) {
	out := new(HandleResponse)
	err := c.cc.Invoke(ctx, HostService_Dispatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, HostService_Log_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, HostService_Query_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, HostService_Exec_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) BeginTx(ctx context.Context, in *BeginTxRequest, opts ...grpc.CallOption) (*BeginTxResponse, error) {
	out := new(BeginTxResponse)
	err := c.cc.Invoke(ctx, HostService_BeginTx_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) CommitTx(ctx context.Context, in *CommitTxRequest, opts ...grpc.CallOption) (*CommitTxResponse, error) {
	out := new(CommitTxResponse)
	err := c.cc.Invoke(ctx, HostService_CommitTx_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) RollbackTx(ctx context.Context, in *RollbackTxRequest, opts ...grpc.CallOption) (*RollbackTxResponse, error) {
	out := new(RollbackTxResponse)
	err := c.cc.Invoke(ctx, HostService_RollbackTx_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility
type HostServiceServer interface {
	// Dispatch übergibt eine (object, action)-Anfrage an den Dispatcher des
	// Hosts, der sie an das zuständige Plugin weiterleitet – nach derselben
	// Match-Logik wie bei Anfragen von außen (siehe PluginService). Das
	// aufrufende Plugin kennt das Ziel-Plugin nicht.
	//
	// Der Host übernimmt request_id, tenant_id und user_id des auslösenden
	// Handle-Aufrufs, sodass Mandant und Berechtigungen über die ganze
	// Aufrufkette erhalten bleiben. Deadlines und Abbruch propagieren über gRPC.
	// Zyklen (A -> B -> A ...) begrenzt der Host über eine maximale
	// Verschachtelungstiefe pro request_id und antwortet dann mit
	// FailedPrecondition. Kein Treffer: Unimplemented.
	Dispatch(context.Context, *HandleRequest) (*HandleResponse, error)
	Log(context.Context, *LogRequest) (*LogResponse, error)
	// Query führt ein SELECT aus und liefert die Zeilen zurück.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Exec führt INSERT/UPDATE/DELETE aus.
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	// Transaktionen
	//
	// Eine Transaktion gilt für genau eine Datenbank und ist an die request_id
	// der Aufrufkette gebunden. Query/Exec laufen in ihr, wenn
	// Context.tx_ids[database] gesetzt ist – auch in Plugins, die über Dispatch
	// aufgerufen wurden. Mehrere Datenbanken werden nicht atomar verbunden.
	//
	// Commit darf nur der Eröffner (gleiche request_id, gleiches Plugin).
	// Rollback darf jeder Teilnehmer auslösen; danach ist die Transaktion
	// abgebrochen und jeder weitere Zugriff bzw. Commit liefert Aborted.
	//
	// Der Host rollt automatisch zurück, wenn die äußerste Anfrage endet, die
	// maximale Laufzeit überschritten ist oder der Plugin-Prozess abstürzt.
	// Die Zahl offener Transaktionen pro Plugin ist begrenzt
	// (ResourceExhausted).
	BeginTx(context.Context, *BeginTxRequest) (*BeginTxResponse, error)
	CommitTx(context.Context, *CommitTxRequest) (*CommitTxResponse, error)
	RollbackTx(context.Context, *RollbackTxRequest) (*RollbackTxResponse, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHostServiceServer struct {
}

func (UnimplementedHostServiceServer) Dispatch(context.Context, *HandleRequest) (*HandleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedHostServiceServer) Log(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedHostServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedHostServiceServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedHostServiceServer) BeginTx(context.Context, *BeginTxRequest) (*BeginTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginTx not implemented")
}
func (UnimplementedHostServiceServer) CommitTx(context.Context, *CommitTxRequest) (*CommitTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitTx not implemented")
}
func (UnimplementedHostServiceServer) RollbackTx(context.Context, *RollbackTxRequest) (*RollbackTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackTx not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s grpc.ServiceRegistrar, srv HostServiceServer) {
	s.RegisterService(&HostService_ServiceDesc, srv)
}

func _HostService_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Dispatch(ctx, req.(*HandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_BeginTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).BeginTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_BeginTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).BeginTx(ctx, req.(*BeginTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_CommitTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).CommitTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_CommitTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).CommitTx(ctx, req.(*CommitTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_RollbackTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).RollbackTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_RollbackTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).RollbackTx(ctx, req.(*RollbackTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostService_ServiceDesc is the grpc.ServiceDesc for HostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coremesh.plugin.v1.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dispatch",
			Handler:    _HostService_Dispatch_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _HostService_Log_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _HostService_Query_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _HostService_Exec_Handler,
		},
		{
			MethodName: "BeginTx",
			Handler:    _HostService_BeginTx_Handler,
		},
		{
			MethodName: "CommitTx",
			Handler:    _HostService_CommitTx_Handler,
		},
		{
			MethodName: "RollbackTx",
			Handler:    _HostService_RollbackTx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/v1/host.proto",
}
