// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PluginService_GetManifest_FullMethodName = "/coremesh.plugin.v1.PluginService/GetManifest"
	PluginService_Configure_FullMethodName   = "/coremesh.plugin.v1.PluginService/Configure"
	PluginService_Handle_FullMethodName      = "/coremesh.plugin.v1.PluginService/Handle"
	PluginService_Read_FullMethodName        = "/coremesh.plugin.v1.PluginService/Read"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginServiceClient interface {
	// GetManifest liefert Identität und Fähigkeiten. Wird direkt nach dem Start
	// aufgerufen; der Dispatcher baut daraus seine (object, action)-Routingtabelle.
	GetManifest(ctx context.Context, in *GetManifestRequest, opts ...grpc.CallOption) (*GetManifestResponse, error)
	// Configure übergibt die pluginspezifischen Einstellungen aus der Host-Config
	// sowie die Broker-ID, unter der das Plugin den HostService erreicht.
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	// Handle verarbeitet eine vom Dispatcher weitergeleitete (object, action).
	Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error)
	// Read liefert das Ergebnis einer (object, action) als Datenstrom – für
	// große Datenmengen, z. B. alle Einzelposten eines Geschäftsjahres für ein
	// Rechenmodul. Routing, Mandant, Benutzer und Berechtigung wie bei Handle;
	// die Action muss im Manifest zusätzlich unter Capability.read_actions
	// stehen, sonst antwortet der Dispatcher mit Unimplemented.
	//
	// Ablauf des Stroms (siehe ReadResponse): genau ein header, dann beliebig
	// viele batch, zum Schluss genau ein end. Ein Fehler mitten im Strom endet
	// als gRPC-Status; bereits gelieferte Zeilen sind dann unvollständig.
	// Gegendruck regelt gRPC: Liest der Empfänger langsamer, wartet der Sender.
	Read(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (PluginService_ReadClient, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) GetManifest(ctx context.Context, in *GetManifestRequest, opts ...grpc.CallOption) (*GetManifestResponse, error) {
	out := new(GetManifestResponse)
	err := c.cc.Invoke(ctx, PluginService_GetManifest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, PluginService_Configure_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error) {
	out := new(HandleResponse)
	err := c.cc.Invoke(ctx, PluginService_Handle_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Read(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (PluginService_ReadClient, error) {
	stream, err := c.cc.NewStream(ctx, &PluginService_ServiceDesc.Streams[0], PluginService_Read_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &pluginServiceReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PluginService_ReadClient interface {
	Recv() (*ReadResponse, error)
	grpc.ClientStream
}

type pluginServiceReadClient struct {
	grpc.ClientStream
}

func (x *pluginServiceReadClient) Recv() (*ReadResponse, error) {
	m := new(ReadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility
type PluginServiceServer interface {
	// GetManifest liefert Identität und Fähigkeiten. Wird direkt nach dem Start
	// aufgerufen; der Dispatcher baut daraus seine (object, action)-Routingtabelle.
	GetManifest(context.Context, *GetManifestRequest) (*GetManifestResponse, error)
	// Configure übergibt die pluginspezifischen Einstellungen aus der Host-Config
	// sowie die Broker-ID, unter der das Plugin den HostService erreicht.
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	// Handle verarbeitet eine vom Dispatcher weitergeleitete (object, action).
	Handle(context.Context, *HandleRequest) (*HandleResponse, error)
	// Read liefert das Ergebnis einer (object, action) als Datenstrom – für
	// große Datenmengen, z. B. alle Einzelposten eines Geschäftsjahres für ein
	// Rechenmodul. Routing, Mandant, Benutzer und Berechtigung wie bei Handle;
	// die Action muss im Manifest zusätzlich unter Capability.read_actions
	// stehen, sonst antwortet der Dispatcher mit Unimplemented.
	//
	// Ablauf des Stroms (siehe ReadResponse): genau ein header, dann beliebig
	// viele batch, zum Schluss genau ein end. Ein Fehler mitten im Strom endet
	// als gRPC-Status; bereits gelieferte Zeilen sind dann unvollständig.
	// Gegendruck regelt gRPC: Liest der Empfänger langsamer, wartet der Sender.
	Read(*HandleRequest, PluginService_ReadServer) error
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPluginServiceServer struct {
}

func (UnimplementedPluginServiceServer) GetManifest(context.Context, *GetManifestRequest) (*GetManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManifest not implemented")
}
func (UnimplementedPluginServiceServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedPluginServiceServer) Handle(context.Context, *HandleRequest) (*HandleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedPluginServiceServer) Read(*HandleRequest, PluginService_ReadServer) error {
	return status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_GetManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetManifest(ctx, req.(*GetManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Handle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Handle(ctx, req.(*HandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HandleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PluginServiceServer).Read(m, &pluginServiceReadServer{stream})
}

type PluginService_ReadServer interface {
	Send(*ReadResponse) error
	grpc.ServerStream
}

type pluginServiceReadServer struct {
	grpc.ServerStream
}

func (x *pluginServiceReadServer) Send(m *ReadResponse) error {
	return x.ServerStream.SendMsg(m)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coremesh.plugin.v1.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManifest",
			Handler:    _PluginService_GetManifest_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _PluginService_Configure_Handler,
		},
		{
			MethodName: "Handle",
			Handler:    _PluginService_Handle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Read",
			Handler:       _PluginService_Read_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin/v1/plugin.proto",
}
